### ISSUE TITLE
XSS Issue in accounts.php

### ISSUE THREAD

**Issue by justinkluever** [Tutorialwork/ProfessionalBans-Webinterface#1]
You can redirect an admin to an url like 
`accounts.php?delete&name=%27%2Balert(%60XSS%60)%2B%27`
to run javascript

file where you can find the issue:
https://github.com/Tutorialwork/ProfessionalBans-Webinterface/blob/00c1e1ac1005c32e2a91271a4996a87d81e9772c/accounts.php#L14

**Comment by Tutorialwork** [comment]
Thank you for your bug report. I have fixed it.
