### ISSUE TITLE
Fehler falls `Notice` meldungen nicht ignoriert werden

### ISSUE THREAD

**Issue by justinkluever** [Tutorialwork/ProfessionalBans-Webinterface#3]
## Problem
Dieses webinterface kann und wird nur funktionieren wenn `Notice` fehler ignoriert werden.

## Beispiele
Diese beispiele sind stark vereinfacht

### Wie das jetzt aussieht
```php
<html>
<?php
 header("Location: /");
 // oder
 session_start();
?>
</html>
```
#### oder
```php
           <?php
            session_start();
           ...
```

### Wie das aussehen darf oder muss:
```php
<?php
 header("Location: /");
 // oder
 session_start();
?>
<html>
 ...
```
oder
```php
<?php
 session_start();
...
```

## Warum?

Sobald auch nur ein bit (irgendwas) ausgegeben wird (z.b. via `echo()` oder einfach vor dem `<?php` tag) werfen funktionen die Header modifizieren fehler.

Falls der server jedoch "Notice" fehler ignoriert kann das durchaus funktionieren, wird jedoch nicht empfohlen (weil das einfach schlechtes codestyle ist) und wird in den logs eine warnung eintragen das dieser fehler gekommen ist jedoch ignoriert wurde.

Weitere infos: https://php-de.github.io/jumpto/headers-already-sent/

Ich hatte ebenfalls eine PR ( #2 ) gemacht um dies zu beheben (zumindest in den meisten dateien) jedoch wurde die nur ignoriert 🤷‍♂

**Comment by Tutorialwork** [comment]
Ist im v3 Branch behoben.
