### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Flockcode** [Tutorialwork/ProfessionalBans-Webinterface#4]
@Tutorialwork 
Hey, your website tutorialwork.de is offline. Can you invite me to your discord?
Thanks

btw. I know you got negative reviews. But I also know, that its really hard, to code such a big Ban System with a Web interface. 

I can't use it at the moment. But I'm sure, I'm going to change soon.

My Tag ist Hohi#1865

**Comment by Tutorialwork** [comment]
I know that my website is currently offline. You can also use this invite link: http://discord.gg/zAyHwsy
