### ISSUE TITLE
Fehler nach dem Installieren

### ISSUE THREAD

**Issue by DxsSucuk** [Tutorialwork/ProfessionalBans-Webinterface#5]
Ich hab mir die neuste Version des Webinterfaces geholt und auf meinem Root server installiert nach dem Installieren kriegen ich diesen fehler auf der seite
Fatal Error: composer.lock was created for PHP version 7.4 or higher but the current PHP version is 7.0.33.

**Comment by DxsSucuk** [comment]
Wenn ich php -v eingebe wird mir gesagt das ich 7.4.6 hab

**Comment by Tutorialwork** [comment]
Versuche mal mit `a2dismod phpX` dein alte Version zu deaktivieren und mit `a2enmod php7.4` die neue Version zu aktivieren danach natürlich Apache2 neustarten mit `service apache2 restart`.
