### ISSUE TITLE
Error 500 nach dem Account Setup

### ISSUE THREAD

**Issue by DxsSucuk** [Tutorialwork/ProfessionalBans-Webinterface#7]
Hey ich kriege immer diesen Fehler nach dem ich den Admin User erstelle
![image](https://user-images.githubusercontent.com/53257574/83328504-bb005c80-a283-11ea-8ea7-661540d51995.png)

**Comment by Niclas-M1** [comment]
Bei mir auch

**Comment by Tutorialwork** [comment]
Das liegt vermutlich daran das die Tabelle in der Datenbank noch nicht existiert. Dies kann behoben werden indem man zuerst das Plugin einrichtet.

**Comment by DxsSucuk** [comment]
jap hab ich gerade versucht das Plugin gibt aber nur diesen Fehler ab
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_u' at line 1

**Comment by Tutorialwork** [comment]
Dieser Fehler wird durch eine veraltete MariaDB Version ausgelöst. Es wird mindestens MariaDB 10.3 benötigt. [Hier ](https://youtu.be/epOJ8QQnt5Y) findest du eine Anleitung wie du ein Upgrade durchführen kannst.
